name: Run tests on Java 17

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run unit tests on Java 17
    steps:
      - uses: actions/checkout@master
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - run: mvn -f pom.xml test
